/* if you're using pannel carefully edit this part

There's no need to configure this if you're deploying via Heroku — just set them in the environment variables.*/

const sessionName = 'session';
const session = process.env.SESSION || 'BLACK-MD:~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUc0VVFMTGJuTGgzWENMSVRZWW5hTU9zYUZkaEVoUGNGWGNaMWpESGlXZz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib1diWFJTQzlNODNaWi9GcWkzbHVMUUdYVFNlUElQNVpIZ2ZORy9VL2dRRT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIrTTlTaGhFV1V0UEIxSTlLSmJ1N3liNitOcHZIeE1RUFp0ZWY2WU04VTFzPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJ2VEtvV1hXSjI5SVR0eVN5aEFZMEE3VElybnFDK2cxNEY4ci9vbkVmVDMwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFLNEhab2hOblo4YWlPSGNucDJHUkVSdHIwVnBEZ0ZFTXBvcjFyY3lwMlE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ind0NFh2cTlXMUJqY1dvclY0V1k3T2ZCdVovUXpzWjJSeTMxMTE3elhzUzA9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNEpCa2ZQblRYY2QzRndGNms4OVlHRFRLa0xPYVZvUmQxY2FTOHBvWnZHcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZGgrb2lpdlRFY2tkcHBaRWpTSE4wMFBGSU1MaXNOMkdCMURhZUcrV0pnaz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImZkdE1yVVpWTGNPcm92VDJ1ZmtNYmVGOW1NZzF2S2JUMVZBSlN4cFNGeGZDSk9RMi9EYlFCaXMrZHhxR3BpL3RyUExJMHBWN2J1bGFoM0UvcUI5ZEJRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjQsImFkdlNlY3JldEtleSI6IjQ2RmhpQ1lsc1R1dDB5ZlBNU2oyK1F5L0x4cGxnYmViWFJMcTd3ZlV1MnM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0Nzk3MzkxODI4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDQzA5N0M0NUVEQTIyRjFGOEFGOTFERjkxOEY4MUYzIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzkzMzY2Njd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5NzM5MTgyOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQzNFMjU1MjU4NjkxNjE1RDVCRTM4QjYwNzlDNDQ5NiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzc5MzM2NjY3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3OTczOTE4MjhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUM0Qjc1MzM1ODc5N0ZDNzk3OUM5NDk4QUIxRDgyNkIifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3OTMzNjY2OH0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0Nzk3MzkxODI4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDMkIxNzI1RUYwODE3Qzk2RUMzOEFCMjBENEZDQjA4In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzkzMzY2Njl9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5NzM5MTgyOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQzcxRkE2NzIxQkE0Q0NBN0M2MTVFQzY4QTg2ODY0OCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzc5MzM2Njg3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3OTczOTE4MjhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUMzOUYzNTMyQ0EzNENEMzE3RDYyQTA4OUI3NUUyOEUifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3OTMzNjcwMH0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0Nzk3MzkxODI4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDMzFDMEU2NURDNzUzQzBERTM0MjhERTU4MzgzRkI3In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzkzMzY3MTd9XSwibmV4dFByZUtleUlkIjo4MTMsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo4MTMsImFjY291bnRTeW5jQ291bnRlciI6NCwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiQkxJWlpBUkQiLCJtZSI6eyJpZCI6IjI1NDc5NzM5MTgyODoxM0BzLndoYXRzYXBwLm5ldCIsImxpZCI6IjUwODA1ODcyNzg3NDU4OjEzQGxpZCIsIm5hbWUiOiLOm8S/xL/GkNCYIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMWExpdVFGRU1tTHV0QUdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJaVGpQMjIzbnFVNUhsaFltMVpIR3lJbzl5c1VuWGM5SHIzK3ZoNldKd2c0PSIsImFjY291bnRTaWduYXR1cmUiOiJDcUVQSEpxZTU0Z1lVbnZ1TW14Y1FkYjFqaWpNL2tkUHk1UlFKenNhOUNtV0NYd3BySU1kRnI2T3hqN0RVRlUwZVBwVjZoQ0xWSUZ3U3FOM2t1Y1RDZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiWk1SQW0zangwalYxRUljRjg2MEEvdFFOenlpV1IxTjRHeVJ0NC9iNDdDSTNXSlV5dE81OFhhYmJYV3dpVWU1eFVVN2NwMXp1ZDVLQWYrZ045UDUyQmc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3OTczOTE4Mjg6MTNAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCV1U0ejl0dDU2bE9SNVlXSnRXUnhzaUtQY3JGSjEzUFI2OS9yNGVsaWNJTyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0EwSUVnZ0kifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzc5MzM2NjY0LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUdscSJ9';
const appname = process.env.APP_NAME || 'midinyano';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝐁𝐋𝐀𝐂𝐊-𝐌𝐃 𝐁𝐎𝐓';
const author = process.env.STICKER_AUTHOR || 'ƓƐИZҠ254';
const packname = process.env.STICKER_PACKNAME || '𝐁𝐋𝐀𝐂𝐊𝐌𝐄𝐑𝐂𝐇𝐀𝐍𝐓';
const dev = process.env.DEV || '254797391828';
const owner = dev.split(",");
const bad = process.env.BAD_WORD || 'fuck,umbwa,kuma,pussy,slut,bitch,cock,stupid';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 10000;
const antiforeign = process.env.ANTIFOREIGN || 'off';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  antiforeign
};
