/* if you're using pannel carefully edit this part

There's no need to configure this if you're deploying via Heroku — just set them in the environment variables.*/

const sessionName = 'session';
const session = process.env.SESSION || 'BLACK-MD:~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUxsNjRRYW5zR2Q0eFBzeVFocDQ4VTdUYnU4SVlpejY3eGJxOEovUGZVdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYWxsOGhibzFaOGhVdzAvcEZXVDFpKzZja2VQZ3hEdWp4Z2I4UFZ3RFRHYz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjRy9LMGFMT3NIZk1jOGRCU3BUS1c4Q2Z0MUt1alcvdWN6SGMwQmxuM0ZVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJuRjB3SHNtOXR4VGUxZnhXV3ZPd2xsS2FmblZVNGp2Q2RCMHU4RmFkNkh3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InNNYUg2cU1Xb0NMcUc2NnVwUDZGa3R4SGd1Tzl4NkIvWnYxQ1R5cG9iVVk9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlZkczRhNGtFMjBzNjUwV0YxdFVEZUl4TmtZTTJUN1hJN0Z5STdqS1VrV1E9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT0dYZEVLRjhWTW5LR2x2bkE4LzdYZlE3b09MWXVZYzNla0h3S0srL05YST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaE91cmZIUmtwYk92UFRKWHh5c2lvbStjeEM0Z1d3ZUkrbVRVMGxmSXIxST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik42R2xvdlQyUGN5cDl6OVRJQzU3T2l3OEpSZG5jVmdCQ3FVcEIwYU9teENyME94VmRtNkJuaFQ5UllNZ1I5SGdFd0hkc1c2MWJNd1dDZWR1aFFjWWd3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTEzLCJhZHZTZWNyZXRLZXkiOiJudzUzL3B1blFmOXRuViswR2V1Z0dQQ3RTVlJ3WndhZ0RLZDRSV01ONXEwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5NzM5MTgyOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQ0RFRDY2Qjg4QUJBMzE5NDE0QzRCNUVEN0Q2RjkwNSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzc5MzA3NDIzfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3OTczOTE4MjhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUNGMjVGMEYxNTE0NjdCQTM1RDY1NTQzRTRBQzA4QjAifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3OTMwNzQyNn0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0Nzk3MzkxODI4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDRDRGQzJCNjRBQ0I5QUVGMzU4OUEyMzUwOTU2ODNFIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzkzMDc0Mjd9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc5NzM5MTgyOEBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiJBQ0NDOTE2REE2NjkwOTdGQTlFQzIyOUYzMkYxMENFNiJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzc5MzA3NDQwfSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3OTczOTE4MjhAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQUMzQzY0RTQwNDg1OEM4QjMwOUVEQzlCNERBNDQyMDkifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc3OTMwNzQ1Mn0seyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0Nzk3MzkxODI4QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFDMTJEMUI4NDA4MDc1OERDNDc5MEQyNUI0MUUzRTNFIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NzkzMDc0Njh9XSwibmV4dFByZUtleUlkIjo4MTMsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo4MTMsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sInJlZ2lzdGVyZWQiOnRydWUsInBhaXJpbmdDb2RlIjoiQkxJWlpBUkQiLCJtZSI6eyJpZCI6IjI1NDc5NzM5MTgyODoxMkBzLndoYXRzYXBwLm5ldCIsImxpZCI6IjUwODA1ODcyNzg3NDU4OjEyQGxpZCIsIm5hbWUiOiLOm8S/xL/GkNCYIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNMWExpdVFGRUl5bnVOQUdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJaVGpQMjIzbnFVNUhsaFltMVpIR3lJbzl5c1VuWGM5SHIzK3ZoNldKd2c0PSIsImFjY291bnRTaWduYXR1cmUiOiJYd3lRN3dzdndiQlJndm5OblJ2bkI0ZEpMU042d0hXd21NTEhraG9HYjFpTS9OZ2xZU3ZyWGErQk1Vck5GSktITjYzRG5rL3BZeThsMUpXNVF2c3pDZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiYkkxZUFWRlZEbkZkdWRvQmJOQ25xMXU0eEpZQlV4SWhpblMvVlVjNDQ2eWJoQlJtaWxWOVhoQkVpRnltZVBJQTZaUDBQeXJlNHcxU1F1bzkzY2tmaXc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3OTczOTE4Mjg6MTJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCV1U0ejl0dDU2bE9SNVlXSnRXUnhzaUtQY3JGSjEzUFI2OS9yNGVsaWNJTyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0EwSUVnZ0kifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzc5MzA3NDIwLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUdscCJ9';
const appname = process.env.APP_NAME || '';
const herokuapi = process.env.HEROKU_API;
const botname = process.env.BOTNAME || '𝐁𝐋𝐀𝐂𝐊-𝐌𝐃 𝐁𝐎𝐓';
const author = process.env.STICKER_AUTHOR || 'ƓƐИZҠ254';
const packname = process.env.STICKER_PACKNAME || '𝐁𝐋𝐀𝐂𝐊𝐌𝐄𝐑𝐂𝐇𝐀𝐍𝐓';
const dev = process.env.DEV || '254797391828';
const owner = dev.split(",");
const bad = process.env.BAD_WORD || 'fuck,umbwa,kuma,pussy,slut,bitch,cock,stupid';
const admin = process.env.ADMIN_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗿𝗲𝘀𝗲𝗿𝘃𝗲𝗱 𝗳𝗼𝗿 𝗔𝗱𝗺𝗶𝗻𝘀!';
const group = process.env.GROUP_ONLY_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝗚𝗿𝗼𝘂𝗽𝘀!';
const botAdmin = process.env.BOT_ADMIN_MSG || '𝗜 𝗻𝗲𝗲𝗱 𝗔𝗱𝗺𝗶𝗻 𝗽𝗿𝗲𝘃𝗶𝗹𝗲𝗱𝗴𝗲𝘀!';
const NotOwner = process.env.NOT_OWNER_MSG || '𝗖𝗼𝗺𝗺𝗮𝗻𝗱 𝗺𝗲𝗮𝗻𝘁 𝗳𝗼𝗿 𝘁𝗵𝗲 𝗼𝘄𝗻𝗲𝗿!';
const mycode = process.env.CODE || '254';
const port = process.env.PORT || 10000;
const antiforeign = process.env.ANTIFOREIGN || 'off';

module.exports = {
  session,
  sessionName,
  author,
  packname,
  dev,
  owner,
  bad,
  group,
  NotOwner,
  botname,
  botAdmin,
  admin,
  mycode,
  herokuapi,
  port,
  appname,
  antiforeign
};
